### ISSUE TITLE
Translate plugin.video.hbogoeu

### ISSUE THREAD

**Issue by arvvoid** [add-ons/translations#3]
Anyone willing to help translate hGo EU add-on, can submit PRs into my upstream repository here: https://github.com/arvvoid/plugin.video.hbogoeu

Only languages in the table below are needed, other languages can be accepted but the content can be pulled only in those languages from the service so would not help much :)

Current status of translations (_STATUS LAST UPDATED 08/1/2021 12:07_):

**[English](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.en_gb/strings.po)** 102 strings in total / POT file

**OK** - ✔, **NEED UPDATE** - ✍, **BAD NEED WORK** - ✖ **MACHINE TRANSLATED** - 🖥️‼️

| Language | Status | ISO code | Untranslated | Last translator | Previous translators |
|-----------|--------|-------------|--------------|----------------|---------------------|
|[Bosnia and Herzegovina](https://github.com/arvvoid/plugin.video.hbogoeu/raw/51fc68c41ec2c65e9bf9e413cdd89156dad926ce/resources/language/resource.language.bs_ba/strings.po)|✖|bs_ba|all|🖥️‼️||
|[Bulgaria](https://github.com/arvvoid/plugin.video.hbogoeu/raw/51fc68c41ec2c65e9bf9e413cdd89156dad926ce/resources/language/resource.language.bg_bg/strings.po)|✖|bg_bg|all|🖥️‼️||
|[Croatia](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.hr_hr/strings.po) |✔|hr_hr|0| @arvvoid||
|[Czech Republic](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.cs_cz/strings.po) |✍|cs_cz|2|@Ike201||
|[Hungary](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.hu_hu/strings.po) |✔|hu_hu|0|@Ajnasz||
|[Macedonia](https://github.com/arvvoid/plugin.video.hbogoeu/raw/51fc68c41ec2c65e9bf9e413cdd89156dad926ce/resources/language/resource.language.mk_mk/strings.po)|✖|mk_mk|all|🖥️‼️||
|Montenegro|✖|cnr_me|all|||
|[Polonia](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.pl_pl/strings.po)| ✔|pl_pl|0|@barqqlsky|@kowalmisiek|
[Portugal](https://github.com/arvvoid/plugin.video.hbogoeu/raw/51fc68c41ec2c65e9bf9e413cdd89156dad926ce/resources/language/resource.language.pt_pt/strings.po)|✖|pt_pt|all|🖥️‼️||
|[Romania](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.ro_ro/strings.po)| ✔|ro_ro|0|@tmihai20||
|[Serbia](https://github.com/arvvoid/plugin.video.hbogoeu/raw/51fc68c41ec2c65e9bf9e413cdd89156dad926ce/resources/language/resource.language.sr_rs@latin/strings.po)|✖|sr_rs@latin|all|🖥️‼️||
|[Slovakia](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.sk_sk/strings.po)|✔|sk_sk|0|@durip||
|[Slovenija](https://github.com/arvvoid/plugin.video.hbogoeu/raw/51fc68c41ec2c65e9bf9e413cdd89156dad926ce/resources/language/resource.language.sl_si/strings.po)|✖|sl_si|all|🖥️‼️||
|[Spain](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.es_es/strings.po) |✍|es_es|2|@boblo1|@jhdgghost|
[Norway](https://github.com/arvvoid/plugin.video.hbogoeu/raw/51fc68c41ec2c65e9bf9e413cdd89156dad926ce/resources/language/resource.language.nb_no/strings.po)|✖|nb_no|all|🖥️‼️||
[Denmark](https://github.com/arvvoid/plugin.video.hbogoeu/raw/51fc68c41ec2c65e9bf9e413cdd89156dad926ce/resources/language/resource.language.da_dk/strings.po)|✖|da_dk|all|🖥️‼️||
|[Sweden](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.sv_se/strings.po)| ✔|sv_se|0|@Sopor|@macardi|
|[Finland](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.fi_fi/strings.po)|✔|fi_fi|0|@jumakki||

_When possible if no translation is available an initial machine translation has been provided to make it easier for new translators._

cc @add-ons/translators

**Comment by dagwieers** [comment]
@arvvoid We do not have teams for all of these languages. I will add them and add you as the Team member. If you find new translators, you can invite them to those teams.

**Comment by dagwieers** [comment]
@arvvoid We also have the possibility to notify teams or have teams review PRs. And for larger teams we can actually round-robin or balance review requests over the team... I haven't tested that yet.

cc @add-ons/bulgarian @add-ons/czech @add-ons/macedonian @add-ons/montenegrin @add-ons/polish @add-ons/portuguese @add-ons/serbian @add-ons/slovenian @add-ons/norwegian @add-ons/danish @add-ons/swedish 

**Update:** Beware that some of these teams currently have no translators in them. We are in need of more translators and maybe should be looking for other Kodi projects for translators.

**Comment by arvvoid** [comment]
@dagwieers Ok, thank you

**Comment by arvvoid** [comment]
Some new strings need a translation

cc @add-ons/bulgarian @add-ons/czech @add-ons/macedonian @add-ons/montenegrin @add-ons/polish @add-ons/portuguese @add-ons/serbian @add-ons/slovenian @add-ons/norwegian @add-ons/danish @add-ons/swedish @add-ons/spanish

**Comment by dagwieers** [comment]
@arvvoid Let me repeat it here for other add-on developers as well. **It is best to ask translators for translating your add-on when you have finished all development for the upcoming release and are ready to release**. If not, it asks a lot more from translators. It also helps keeping things synchronized if there are fewer events.

We recommend giving it 2 or 3 days for active translators to contribute translations before release. Everything that is translated later will ship with the next release (or a minor release update when you have collected a handful of new translations).

It is also very much appreciated if new features that add translation strings, that they update the strings for _all_ languages. We have checks to report inconsistent translation files if you want to test this. This will ensure that no PR will introduce such inconsistencies unknowningly.

**Comment by arvvoid** [comment]
Hello, @dagwieers I agree, and that is what I do, I see that I worded my request for translation poorly this time. I always accept translations but notify and ask for translations only when a release is imminent and no new strings are expected, usually wait a week or two for translations to come in before releasing, this time I got most translations (active) the same day I asked, and the release contained a fix to an issue that prevent a few users from using the add-on at all so I released right away, what is sent now will make it in the next release.
There will be no new strings for some time now, when I add new strings I sync all translation files (with Poedit) and already have automatic language files cheks in place, will look at your checks as well.
At the moment I don't sync the ones marked with ✖ but those are removed at the moment because unmaintained (those were just an initial machine translation) if they get resurrected those will get included again. If someone is interested in translating those I can sync it a and machine translate it if it makes it easier for new translators.

**Comment by dagwieers** [comment]
@arvvoid I understand, no worries. I just wanted to make the remark because we never discussed this explicitly. I think we need to write this down somewhere on the Wiki.

**Comment by arvvoid** [comment]
Hello, a new release will be made soon. I will wait for translation submissions until Friday 18/12/2020, publishing a new release on Saturday 19/12/2020.
Most maintained translations need only minimal effort 2 strings (non-critical, very rarely seen).

If someone is interested in translating one of the currently unmaintained languages, let me know, I can wait a little longer in that case if needed.

cc @add-ons/translators

**Comment by tmihai20** [comment]
Translated the 2 new strings (which are at the very end) with PR https://github.com/arvvoid/plugin.video.hbogoeu/pull/175.

**Comment by jumakki** [comment]
Here is Finnish translation with 2 new strings
[strings.fi.txt](https://github.com/add-ons/translations/files/5689766/strings.fi.txt)

**Comment by arvvoid** [comment]
The add-on reached End Of Life, Hbo Go service replaced by Hbo Max in all regions
